//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultObject.Core.i18n {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validator_ResultMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validator_ResultMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResultObject.Core.i18n.Validator_ResultMessages", typeof(Validator_ResultMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{collectionName}&quot; collection must contain at least one value..
        /// </summary>
        public static string Message_Collection_Empty {
            get {
                return ResourceManager.GetString("Message_Collection_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{collectionName}&quot; collection must contain at least {count} value(s)..
        /// </summary>
        public static string Message_Collection_NotEnoughValues {
            get {
                return ResourceManager.GetString("Message_Collection_NotEnoughValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{collectionName}&quot; collection cannot contain more than {count} value(s)..
        /// </summary>
        public static string Message_Collection_TooManyValues {
            get {
                return ResourceManager.GetString("Message_Collection_TooManyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field is not a valid credit card number..
        /// </summary>
        public static string Message_CreditCard_Invalid {
            get {
                return ResourceManager.GetString("Message_CreditCard_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field is not a valid e-mail address..
        /// </summary>
        public static string Message_EmailAddress_Invalid {
            get {
                return ResourceManager.GetString("Message_EmailAddress_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field only accepts files with the following extensions - &quot;{fileExtensions}&quot;..
        /// </summary>
        public static string Message_FileExtensions_NotSupported {
            get {
                return ResourceManager.GetString("Message_FileExtensions_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;{propertyName}&quot; must be a string or array type with a maximum length of {maxLength}..
        /// </summary>
        public static string Message_MaxLength_Exceeded {
            get {
                return ResourceManager.GetString("Message_MaxLength_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;{propertyName}&quot; must be a string with a maximum length of {maxLength}..
        /// </summary>
        public static string Message_MaxStringLength_Exceeded {
            get {
                return ResourceManager.GetString("Message_MaxStringLength_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;{propertyName}&quot; must be a string with a minimum length of {minLength}..
        /// </summary>
        public static string Message_MinStringLength_Violation {
            get {
                return ResourceManager.GetString("Message_MinStringLength_Violation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{objectName}&quot; object is required..
        /// </summary>
        public static string Message_Object_Required {
            get {
                return ResourceManager.GetString("Message_Object_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field is not a valid phone number..
        /// </summary>
        public static string Message_Phone_Invalid {
            get {
                return ResourceManager.GetString("Message_Phone_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field is required..
        /// </summary>
        public static string Message_Property_Required {
            get {
                return ResourceManager.GetString("Message_Property_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;{propertyName}&quot; must be between {min} and {max}..
        /// </summary>
        public static string Message_Range_Violation {
            get {
                return ResourceManager.GetString("Message_Range_Violation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;{propertyName}&quot; must match the regular expression &quot;{regex}&quot;..
        /// </summary>
        public static string Message_Regex_NoMatch {
            get {
                return ResourceManager.GetString("Message_Regex_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;{propertyName}&quot; must be a string with a minimum length of {minLength} and a maximum length of {maxLength}..
        /// </summary>
        public static string Message_StringLengthRange_Violation {
            get {
                return ResourceManager.GetString("Message_StringLengthRange_Violation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field is not a valid fully-qualified http, https, or ftp url..
        /// </summary>
        public static string Message_Url_Invalid {
            get {
                return ResourceManager.GetString("Message_Url_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field is not valid..
        /// </summary>
        public static string Message_Value_Invalid {
            get {
                return ResourceManager.GetString("Message_Value_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyNameOne}&quot; field must be greater than the &quot;{propertyNameTwo}&quot; field..
        /// </summary>
        public static string Message_Value_NotGreaterThan {
            get {
                return ResourceManager.GetString("Message_Value_NotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyNameOne}&quot; field must be greater than or equal to the &quot;{propertyNameTwo}&quot; field..
        /// </summary>
        public static string Message_Value_NotGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("Message_Value_NotGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field must be greater than or equal to {value}..
        /// </summary>
        public static string Message_Value_NotGreaterThanOrEqualToValue {
            get {
                return ResourceManager.GetString("Message_Value_NotGreaterThanOrEqualToValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field must be greater than {value}..
        /// </summary>
        public static string Message_Value_NotGreaterThanValue {
            get {
                return ResourceManager.GetString("Message_Value_NotGreaterThanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyNameOne}&quot; field must be less than the &quot;{propertyNameTwo}&quot; field..
        /// </summary>
        public static string Message_Value_NotLessThan {
            get {
                return ResourceManager.GetString("Message_Value_NotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyNameOne}&quot; field must be less than or equal to the &quot;{propertyNameTwo}&quot; field..
        /// </summary>
        public static string Message_Value_NotLessThanOrEqual {
            get {
                return ResourceManager.GetString("Message_Value_NotLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field must be less than or equal to {value}..
        /// </summary>
        public static string Message_Value_NotLessThanOrEqualToValue {
            get {
                return ResourceManager.GetString("Message_Value_NotLessThanOrEqualToValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field must be less than {value}..
        /// </summary>
        public static string Message_Value_NotLessThanValue {
            get {
                return ResourceManager.GetString("Message_Value_NotLessThanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{propertyValue}&quot; is not a valid value for &quot;{propertyName}&quot; field..
        /// </summary>
        public static string Message_Value_NotSet {
            get {
                return ResourceManager.GetString("Message_Value_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field must be greater than &quot;{min}&quot; and less than &quot;{max}&quot;..
        /// </summary>
        public static string Message_Value_NotWithinExclusiveRange {
            get {
                return ResourceManager.GetString("Message_Value_NotWithinExclusiveRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field must be greater than or equal to &quot;{min}&quot; and less than or equal to &quot;{max}&quot;..
        /// </summary>
        public static string Message_Value_NotWithinInclusiveRange {
            get {
                return ResourceManager.GetString("Message_Value_NotWithinInclusiveRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field must be greater than &quot;{min}&quot; and less than or equal to &quot;{max}&quot;..
        /// </summary>
        public static string Message_Value_NotWithinMaxInclusiveRange {
            get {
                return ResourceManager.GetString("Message_Value_NotWithinMaxInclusiveRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{propertyName}&quot; field must be greater than or equal to &quot;{min}&quot; and less than &quot;{max}&quot;..
        /// </summary>
        public static string Message_Value_NotWithinMinInclusiveRange {
            get {
                return ResourceManager.GetString("Message_Value_NotWithinMinInclusiveRange", resourceCulture);
            }
        }
    }
}
